### ISSUE TITLE
How to get cookie.txt

### ISSUE THREAD

**Issue by vwxyzjn** [Smart-Hypercube/Weibo-API#1]
Hi,

Thank you for developing the package. So I am trying to crawl all the weibo posts of one user and I cloned your repo to experiment with it. I notice that in your ``weibo.py`` file, you opened a file called ``cookie.txt`` and I am wondering where is the file from?

I try to generate a ``cookie.txt`` by using a chrome extension at [https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en), but the program had an exception that says

    raise ValueError('Invalid header value %r' % (values[i],))
    
    ValueError: Invalid header value b'# HTTP Cookie File downloaded with cookies.txt by Genuinous @genuinous\n# This file can be used by wget, curl, aria2c and other standard complainant tools.\n# Usage Examples:\n#   1) wget -x --load-cookies cookies.txt "chrome-extension://njabckikapfpffapmjgojcnbfjonfjfg/welcome/welcome.html"\n#   2) curl --cookie cookies.txt "chrome-extension://njabckikapfpffapmjgojcnbfjonfjfg/welcome/welcome.html"\n#   3) aria2c --load-cookies cookies.txt "chrome-extension://njabckikapfpffapmjgojcnbfjonfjfg/welcome/welcome.html"\n#\nwww.valuecoders.com\tFALSE\t/blog/technology-and-apps/top-javascript-frameworks-list-comparison\tFALSE\t1504567527\t__smVI
    ....

How should I fix it?

**Comment by SmartHypercube** [comment]
I apologize for the inconvenience. I just updated README.md and hope it will be helpful.

If you still have any questions, please feel free to ask here~
